name: Master
on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 5 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Running
      run: |
        echo " 22f1001592@ds.study.iitm.ac.in"
