name: Daily Commit

on:
  schedule:
    - cron: '0 8 * * *'  # Runs every day at 08:00 UTC
  workflow_dispatch:     # Optional: allows manual triggering

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Make a change with email 22f1001592@ds.study.iitm.ac.in
        run: |
          echo "Daily update at $(date)" >> daily-log.txt

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "22f1001592@ds.study.iitm.ac.in"
          git add .
          git commit -m "Automated daily commit: $(date)" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
