name: Daily Commit

on:
  schedule:
    - cron: '30 5 * * *'  # daily at 05:30 UTC

permissions:
  contents: write

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Git
      run: |
        git config --global user.name "GitHub Action Bot"
        git config --global user.email "22f1001592@ds.study.iitm.ac.in"

    - name: Make empty commit for 22f1001592@ds.study.iitm.ac.in
      run: |
        git commit --allow-empty -m "Daily commit: $(date)"

    - name: Push commit
      run: |
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:$(git rev-parse --abbrev-ref HEAD)
